// Searchable icon dataset with keywords
// Each icon has associated search terms for easy discovery

export interface SearchableIcon {
  emoji: string;
  keywords: string[];
}

export const SEARCHABLE_ICONS: SearchableIcon[] = [
  // ACTION & POWER
  { emoji: '🚀', keywords: ['rocket', 'launch', 'start', 'fast', 'speed', 'space', 'blast', 'takeoff'] },
  { emoji: '⚡', keywords: ['lightning', 'power', 'energy', 'fast', 'electric', 'bolt', 'quick', 'flash'] },
  { emoji: '💥', keywords: ['explosion', 'boom', 'impact', 'crash', 'bang', 'burst', 'power'] },
  { emoji: '🔥', keywords: ['fire', 'hot', 'flame', 'burn', 'trending', 'popular', 'lit'] },
  { emoji: '💪', keywords: ['strong', 'muscle', 'power', 'strength', 'fitness', 'gym', 'workout', 'arm'] },
  { emoji: '🎯', keywords: ['target', 'goal', 'aim', 'focus', 'bullseye', 'dart', 'objective', 'hit'] },
  { emoji: '⚔️', keywords: ['sword', 'battle', 'fight', 'combat', 'war', 'crossed', 'weapon'] },
  { emoji: '🛡️', keywords: ['shield', 'protect', 'defense', 'guard', 'security', 'safe'] },
  { emoji: '🏹', keywords: ['bow', 'arrow', 'archery', 'aim', 'hunt', 'target'] },
  { emoji: '💣', keywords: ['bomb', 'explosive', 'danger', 'blast', 'boom'] },
  { emoji: '🧨', keywords: ['dynamite', 'explosive', 'firecracker', 'boom', 'blast'] },
  { emoji: '🗡️', keywords: ['dagger', 'sword', 'knife', 'blade', 'weapon', 'cut'] },
  { emoji: '🔨', keywords: ['hammer', 'tool', 'build', 'construct', 'fix', 'nail', 'work'] },
  { emoji: '⛏️', keywords: ['pickaxe', 'mine', 'dig', 'tool', 'minecraft', 'work'] },
  { emoji: '🪓', keywords: ['axe', 'chop', 'wood', 'cut', 'tool', 'lumber'] },
  { emoji: '🔧', keywords: ['wrench', 'tool', 'fix', 'repair', 'settings', 'configure'] },
  { emoji: '🛠️', keywords: ['tools', 'hammer', 'wrench', 'fix', 'build', 'repair', 'work'] },
  { emoji: '⚙️', keywords: ['gear', 'settings', 'cog', 'mechanism', 'config', 'system'] },
  { emoji: '🔩', keywords: ['nut', 'bolt', 'screw', 'hardware', 'metal', 'fix'] },

  // MOVEMENT & TRANSPORT
  { emoji: '🏃', keywords: ['run', 'running', 'sprint', 'fast', 'exercise', 'jog', 'race'] },
  { emoji: '🚴', keywords: ['bike', 'bicycle', 'cycling', 'ride', 'exercise', 'sport'] },
  { emoji: '🏊', keywords: ['swim', 'swimming', 'pool', 'water', 'sport', 'exercise'] },
  { emoji: '⛷️', keywords: ['ski', 'skiing', 'snow', 'winter', 'mountain', 'sport'] },
  { emoji: '🏂', keywords: ['snowboard', 'snow', 'winter', 'mountain', 'sport'] },
  { emoji: '🚗', keywords: ['car', 'drive', 'auto', 'vehicle', 'transport', 'road'] },
  { emoji: '🏎️', keywords: ['race', 'racing', 'car', 'fast', 'speed', 'formula'] },
  { emoji: '✈️', keywords: ['plane', 'airplane', 'fly', 'flight', 'travel', 'air', 'trip'] },
  { emoji: '🛩️', keywords: ['plane', 'small', 'aircraft', 'fly', 'private'] },
  { emoji: '🚁', keywords: ['helicopter', 'fly', 'chopper', 'air', 'rescue'] },
  { emoji: '🛸', keywords: ['ufo', 'alien', 'space', 'flying', 'saucer', 'spaceship'] },
  { emoji: '🚄', keywords: ['train', 'fast', 'bullet', 'rail', 'transport', 'speed'] },
  { emoji: '🚅', keywords: ['train', 'shinkansen', 'bullet', 'fast', 'japan'] },
  { emoji: '🚂', keywords: ['train', 'locomotive', 'steam', 'railway', 'engine'] },
  { emoji: '🛵', keywords: ['scooter', 'moped', 'ride', 'vespa', 'motor'] },
  { emoji: '🏍️', keywords: ['motorcycle', 'bike', 'ride', 'motor', 'fast'] },
  { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycle', 'ride', 'pedal'] },
  { emoji: '⛵', keywords: ['sailboat', 'sail', 'boat', 'water', 'sea', 'yacht'] },
  { emoji: '🚤', keywords: ['speedboat', 'boat', 'fast', 'water', 'motor'] },
  { emoji: '🛥️', keywords: ['motorboat', 'boat', 'yacht', 'water', 'cruise'] },
  { emoji: '🪂', keywords: ['parachute', 'skydive', 'fall', 'jump', 'air'] },
  { emoji: '🎿', keywords: ['ski', 'skiing', 'snow', 'winter', 'sport'] },
  { emoji: '🏄', keywords: ['surf', 'surfing', 'wave', 'beach', 'ocean', 'sport'] },
  { emoji: '🚶', keywords: ['walk', 'walking', 'person', 'pedestrian', 'stroll'] },
  { emoji: '🧗', keywords: ['climb', 'climbing', 'rock', 'mountain', 'sport'] },
  { emoji: '🪁', keywords: ['kite', 'fly', 'wind', 'play', 'sky'] },
  { emoji: '➡️', keywords: ['arrow', 'right', 'next', 'forward', 'direction', 'go'] },
  { emoji: '⬆️', keywords: ['arrow', 'up', 'north', 'direction', 'rise', 'increase'] },
  { emoji: '↗️', keywords: ['arrow', 'diagonal', 'up', 'right', 'growth', 'increase'] },
  { emoji: '🔄', keywords: ['refresh', 'reload', 'sync', 'rotate', 'repeat', 'cycle'] },
  { emoji: '♻️', keywords: ['recycle', 'green', 'eco', 'environment', 'reuse'] },
  { emoji: '🔀', keywords: ['shuffle', 'random', 'mix', 'swap', 'change'] },
  { emoji: '🔁', keywords: ['repeat', 'loop', 'again', 'replay', 'cycle'] },

  // TECHNOLOGY & DIGITAL
  { emoji: '💻', keywords: ['laptop', 'computer', 'mac', 'work', 'code', 'tech', 'programming'] },
  { emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor', 'screen', 'pc', 'display'] },
  { emoji: '📱', keywords: ['phone', 'mobile', 'smartphone', 'iphone', 'android', 'cell'] },
  { emoji: '📲', keywords: ['phone', 'mobile', 'call', 'incoming', 'arrow'] },
  { emoji: '⌨️', keywords: ['keyboard', 'type', 'typing', 'computer', 'input'] },
  { emoji: '🖱️', keywords: ['mouse', 'computer', 'click', 'cursor', 'pointer'] },
  { emoji: '💾', keywords: ['floppy', 'disk', 'save', 'storage', 'data', 'retro'] },
  { emoji: '💿', keywords: ['cd', 'disc', 'music', 'dvd', 'storage', 'album'] },
  { emoji: '📀', keywords: ['dvd', 'disc', 'movie', 'video', 'storage'] },
  { emoji: '🔌', keywords: ['plug', 'electric', 'power', 'connect', 'outlet'] },
  { emoji: '🔋', keywords: ['battery', 'power', 'charge', 'energy', 'full'] },
  { emoji: '📡', keywords: ['satellite', 'antenna', 'signal', 'broadcast', 'wireless'] },
  { emoji: '📺', keywords: ['tv', 'television', 'screen', 'watch', 'show', 'video'] },
  { emoji: '📻', keywords: ['radio', 'music', 'broadcast', 'audio', 'listen'] },
  { emoji: '🎮', keywords: ['game', 'gaming', 'controller', 'play', 'video', 'console'] },
  { emoji: '🕹️', keywords: ['joystick', 'game', 'arcade', 'play', 'retro', 'control'] },
  { emoji: '🤖', keywords: ['robot', 'ai', 'bot', 'machine', 'android', 'automation'] },
  { emoji: '🦾', keywords: ['robot', 'arm', 'prosthetic', 'mechanical', 'bionic'] },
  { emoji: '🦿', keywords: ['robot', 'leg', 'prosthetic', 'mechanical', 'bionic'] },
  { emoji: '🧬', keywords: ['dna', 'genetics', 'science', 'biology', 'helix', 'gene'] },
  { emoji: '🔬', keywords: ['microscope', 'science', 'research', 'lab', 'biology', 'study'] },
  { emoji: '🔭', keywords: ['telescope', 'space', 'astronomy', 'stars', 'observe', 'look'] },
  { emoji: '⚗️', keywords: ['chemistry', 'science', 'lab', 'experiment', 'flask', 'potion'] },
  { emoji: '🧪', keywords: ['test', 'tube', 'science', 'lab', 'experiment', 'chemistry'] },
  { emoji: '🧫', keywords: ['petri', 'dish', 'science', 'lab', 'biology', 'bacteria'] },
  { emoji: '🧲', keywords: ['magnet', 'attract', 'magnetic', 'pull', 'physics'] },
  { emoji: '💡', keywords: ['idea', 'bulb', 'light', 'bright', 'think', 'innovation', 'creative'] },
  { emoji: '🔦', keywords: ['flashlight', 'light', 'torch', 'bright', 'dark', 'search'] },
  { emoji: '📸', keywords: ['camera', 'photo', 'picture', 'snap', 'flash', 'photography'] },
  { emoji: '📹', keywords: ['video', 'camera', 'record', 'film', 'movie', 'camcorder'] },
  { emoji: '🎥', keywords: ['movie', 'camera', 'film', 'cinema', 'hollywood', 'video'] },
  { emoji: '📽️', keywords: ['projector', 'film', 'movie', 'cinema', 'presentation'] },
  { emoji: '🎬', keywords: ['clapper', 'movie', 'film', 'action', 'cinema', 'director'] },

  // BUSINESS & FINANCE
  { emoji: '💼', keywords: ['briefcase', 'business', 'work', 'job', 'office', 'professional'] },
  { emoji: '📊', keywords: ['chart', 'graph', 'data', 'statistics', 'analytics', 'bar'] },
  { emoji: '📈', keywords: ['chart', 'growth', 'increase', 'up', 'stock', 'profit', 'trending'] },
  { emoji: '📉', keywords: ['chart', 'down', 'decrease', 'loss', 'decline', 'fall'] },
  { emoji: '💰', keywords: ['money', 'bag', 'cash', 'rich', 'wealth', 'dollar', 'finance'] },
  { emoji: '💵', keywords: ['money', 'dollar', 'cash', 'bill', 'currency', 'payment'] },
  { emoji: '💳', keywords: ['credit', 'card', 'payment', 'debit', 'bank', 'buy'] },
  { emoji: '🏦', keywords: ['bank', 'money', 'finance', 'building', 'institution'] },
  { emoji: '🏢', keywords: ['office', 'building', 'business', 'work', 'corporate', 'company'] },
  { emoji: '🏗️', keywords: ['construction', 'building', 'crane', 'work', 'development'] },
  { emoji: '🏭', keywords: ['factory', 'industry', 'manufacturing', 'production', 'industrial'] },
  { emoji: '📋', keywords: ['clipboard', 'list', 'task', 'checklist', 'notes', 'todo'] },
  { emoji: '📌', keywords: ['pin', 'pushpin', 'location', 'mark', 'important', 'attach'] },
  { emoji: '📍', keywords: ['pin', 'location', 'map', 'place', 'mark', 'gps'] },
  { emoji: '🗂️', keywords: ['folder', 'files', 'organize', 'dividers', 'tabs', 'index'] },
  { emoji: '📑', keywords: ['bookmark', 'tabs', 'document', 'pages', 'paper'] },
  { emoji: '📄', keywords: ['document', 'page', 'paper', 'file', 'text', 'blank'] },
  { emoji: '📃', keywords: ['document', 'page', 'paper', 'curl', 'scroll'] },
  { emoji: '📝', keywords: ['memo', 'note', 'write', 'pencil', 'document', 'edit'] },
  { emoji: '✏️', keywords: ['pencil', 'write', 'edit', 'draw', 'school', 'yellow'] },
  { emoji: '🖊️', keywords: ['pen', 'write', 'ink', 'ballpoint', 'sign'] },
  { emoji: '🖋️', keywords: ['pen', 'fountain', 'write', 'ink', 'fancy', 'signature'] },
  { emoji: '📧', keywords: ['email', 'mail', 'message', 'inbox', 'letter', 'send'] },
  { emoji: '📨', keywords: ['email', 'envelope', 'incoming', 'mail', 'receive'] },
  { emoji: '📩', keywords: ['email', 'envelope', 'down', 'arrow', 'receive', 'inbox'] },
  { emoji: '📤', keywords: ['outbox', 'send', 'upload', 'mail', 'tray'] },
  { emoji: '📥', keywords: ['inbox', 'receive', 'download', 'mail', 'tray'] },
  { emoji: '📦', keywords: ['package', 'box', 'shipping', 'delivery', 'parcel', 'gift'] },
  { emoji: '🏷️', keywords: ['tag', 'label', 'price', 'sale', 'name', 'category'] },
  { emoji: '🔖', keywords: ['bookmark', 'save', 'mark', 'ribbon', 'favorite'] },
  { emoji: '📎', keywords: ['paperclip', 'attach', 'attachment', 'clip', 'office'] },
  { emoji: '🔗', keywords: ['link', 'chain', 'url', 'connect', 'web', 'hyperlink'] },
  { emoji: '📐', keywords: ['triangle', 'ruler', 'math', 'geometry', 'measure', 'angle'] },
  { emoji: '📏', keywords: ['ruler', 'measure', 'straight', 'length', 'inch'] },
  { emoji: '🗓️', keywords: ['calendar', 'date', 'schedule', 'planner', 'month', 'spiral'] },
  { emoji: '📅', keywords: ['calendar', 'date', 'schedule', 'event', 'day', 'month'] },
  { emoji: '⏰', keywords: ['alarm', 'clock', 'time', 'wake', 'morning', 'reminder'] },
  { emoji: '⏱️', keywords: ['stopwatch', 'timer', 'time', 'fast', 'race', 'speed'] },
  { emoji: '⏲️', keywords: ['timer', 'clock', 'countdown', 'cooking', 'time'] },
  { emoji: '🔔', keywords: ['bell', 'notification', 'alert', 'ring', 'reminder', 'alarm'] },
  { emoji: '📣', keywords: ['megaphone', 'announce', 'loud', 'shout', 'marketing', 'promotion'] },

  // CREATIVITY & ARTS
  { emoji: '🎨', keywords: ['art', 'palette', 'paint', 'color', 'creative', 'design', 'artist'] },
  { emoji: '🖌️', keywords: ['brush', 'paint', 'art', 'draw', 'creative', 'design'] },
  { emoji: '🖍️', keywords: ['crayon', 'draw', 'color', 'art', 'kids', 'creative'] },
  { emoji: '✨', keywords: ['sparkle', 'stars', 'magic', 'shine', 'glitter', 'new', 'special'] },
  { emoji: '🌟', keywords: ['star', 'glow', 'shine', 'bright', 'glowing', 'excellent'] },
  { emoji: '⭐', keywords: ['star', 'favorite', 'rating', 'best', 'gold', 'top'] },
  { emoji: '💫', keywords: ['dizzy', 'star', 'shooting', 'magic', 'sparkle', 'wow'] },
  { emoji: '🎭', keywords: ['theater', 'drama', 'masks', 'acting', 'performance', 'arts'] },
  { emoji: '🎪', keywords: ['circus', 'tent', 'carnival', 'show', 'performance', 'fun'] },
  { emoji: '🎤', keywords: ['microphone', 'sing', 'karaoke', 'music', 'speak', 'voice'] },
  { emoji: '🎧', keywords: ['headphones', 'music', 'audio', 'listen', 'dj', 'podcast'] },
  { emoji: '🎼', keywords: ['music', 'score', 'notes', 'song', 'melody', 'compose'] },
  { emoji: '🎹', keywords: ['piano', 'keyboard', 'music', 'keys', 'instrument', 'play'] },
  { emoji: '🎸', keywords: ['guitar', 'music', 'rock', 'play', 'instrument', 'band'] },
  { emoji: '🎺', keywords: ['trumpet', 'music', 'brass', 'jazz', 'instrument', 'horn'] },
  { emoji: '🎻', keywords: ['violin', 'music', 'classical', 'string', 'instrument', 'orchestra'] },
  { emoji: '🥁', keywords: ['drum', 'music', 'beat', 'percussion', 'instrument', 'band'] },
  { emoji: '🎷', keywords: ['saxophone', 'music', 'jazz', 'instrument', 'sax', 'blues'] },
  { emoji: '📷', keywords: ['camera', 'photo', 'picture', 'photography', 'snap', 'shoot'] },
  { emoji: '🎞️', keywords: ['film', 'frames', 'movie', 'cinema', 'photography', 'strip'] },
  { emoji: '📚', keywords: ['books', 'library', 'read', 'study', 'learn', 'education', 'stack'] },
  { emoji: '📖', keywords: ['book', 'open', 'read', 'study', 'learn', 'education'] },
  { emoji: '📔', keywords: ['notebook', 'journal', 'diary', 'write', 'notes'] },
  { emoji: '📓', keywords: ['notebook', 'journal', 'write', 'notes', 'school'] },
  { emoji: '📕', keywords: ['book', 'red', 'closed', 'read', 'study'] },
  { emoji: '📗', keywords: ['book', 'green', 'read', 'study', 'textbook'] },
  { emoji: '📘', keywords: ['book', 'blue', 'read', 'study', 'textbook'] },
  { emoji: '📙', keywords: ['book', 'orange', 'read', 'study', 'textbook'] },
  { emoji: '✍️', keywords: ['write', 'writing', 'hand', 'sign', 'author', 'compose'] },
  { emoji: '🖼️', keywords: ['frame', 'picture', 'art', 'painting', 'gallery', 'image'] },
  { emoji: '🎁', keywords: ['gift', 'present', 'birthday', 'christmas', 'wrapped', 'surprise'] },
  { emoji: '🎀', keywords: ['ribbon', 'bow', 'gift', 'decoration', 'pink', 'cute'] },
  { emoji: '🎊', keywords: ['confetti', 'party', 'celebrate', 'ball', 'festival'] },
  { emoji: '🎉', keywords: ['party', 'celebrate', 'popper', 'tada', 'congratulations', 'hooray'] },
  { emoji: '🏆', keywords: ['trophy', 'winner', 'champion', 'award', 'first', 'prize', 'gold'] },
  { emoji: '🥇', keywords: ['gold', 'medal', 'first', 'winner', 'champion', 'best'] },
  { emoji: '🥈', keywords: ['silver', 'medal', 'second', 'runner', 'place'] },
  { emoji: '🥉', keywords: ['bronze', 'medal', 'third', 'place', 'award'] },
  { emoji: '🏅', keywords: ['medal', 'sports', 'award', 'achievement', 'winner'] },

  // IDEAS & THINKING
  { emoji: '🧠', keywords: ['brain', 'think', 'mind', 'smart', 'intelligence', 'idea', 'mental'] },
  { emoji: '💭', keywords: ['thought', 'bubble', 'think', 'idea', 'dream', 'cloud'] },
  { emoji: '💬', keywords: ['speech', 'bubble', 'talk', 'chat', 'message', 'comment', 'say'] },
  { emoji: '❓', keywords: ['question', 'mark', 'ask', 'help', 'what', 'why', 'how'] },
  { emoji: '❗', keywords: ['exclamation', 'important', 'alert', 'warning', 'attention'] },
  { emoji: '💯', keywords: ['hundred', 'perfect', 'score', 'full', 'complete', 'best'] },
  { emoji: '🔮', keywords: ['crystal', 'ball', 'future', 'magic', 'fortune', 'predict'] },
  { emoji: '🎱', keywords: ['pool', 'billiard', 'eight', 'ball', 'game', 'magic'] },
  { emoji: '🧿', keywords: ['evil', 'eye', 'nazar', 'protection', 'luck', 'charm'] },
  { emoji: '🔍', keywords: ['search', 'magnify', 'zoom', 'find', 'look', 'investigate', 'glass'] },
  { emoji: '🔎', keywords: ['search', 'magnify', 'zoom', 'find', 'look', 'right'] },
  { emoji: '👁️', keywords: ['eye', 'look', 'see', 'watch', 'vision', 'view'] },
  { emoji: '👀', keywords: ['eyes', 'look', 'see', 'watch', 'stare', 'peek'] },
  { emoji: '🧐', keywords: ['monocle', 'inspect', 'curious', 'examine', 'investigate', 'think'] },
  { emoji: '🤔', keywords: ['think', 'thinking', 'hmm', 'consider', 'wonder', 'ponder'] },
  { emoji: '🎓', keywords: ['graduate', 'cap', 'education', 'school', 'university', 'degree'] },
  { emoji: '✅', keywords: ['check', 'done', 'complete', 'yes', 'correct', 'verified', 'approved'] },
  { emoji: '☑️', keywords: ['check', 'box', 'done', 'complete', 'ballot', 'vote'] },

  // NATURE & GROWTH
  { emoji: '🌱', keywords: ['seedling', 'plant', 'grow', 'growth', 'sprout', 'new', 'spring'] },
  { emoji: '🌿', keywords: ['herb', 'plant', 'leaf', 'nature', 'green', 'natural'] },
  { emoji: '🍀', keywords: ['clover', 'luck', 'lucky', 'four', 'leaf', 'irish', 'shamrock'] },
  { emoji: '🌳', keywords: ['tree', 'nature', 'forest', 'deciduous', 'wood', 'plant'] },
  { emoji: '🌲', keywords: ['evergreen', 'tree', 'pine', 'christmas', 'nature', 'forest'] },
  { emoji: '🌴', keywords: ['palm', 'tree', 'tropical', 'beach', 'vacation', 'island'] },
  { emoji: '🌵', keywords: ['cactus', 'desert', 'plant', 'dry', 'succulent'] },
  { emoji: '🌸', keywords: ['cherry', 'blossom', 'flower', 'spring', 'pink', 'japan', 'sakura'] },
  { emoji: '🌺', keywords: ['hibiscus', 'flower', 'tropical', 'hawaii', 'pink', 'plant'] },
  { emoji: '🌻', keywords: ['sunflower', 'flower', 'yellow', 'sun', 'happy', 'summer'] },
  { emoji: '🌹', keywords: ['rose', 'flower', 'red', 'love', 'romantic', 'valentine'] },
  { emoji: '🌷', keywords: ['tulip', 'flower', 'spring', 'pink', 'plant', 'garden'] },
  { emoji: '💐', keywords: ['bouquet', 'flowers', 'gift', 'wedding', 'arrangement'] },
  { emoji: '🍃', keywords: ['leaf', 'leaves', 'wind', 'nature', 'green', 'blow'] },
  { emoji: '🍂', keywords: ['fallen', 'leaf', 'autumn', 'fall', 'brown', 'nature'] },
  { emoji: '🍁', keywords: ['maple', 'leaf', 'canada', 'autumn', 'fall', 'red'] },
  { emoji: '🌾', keywords: ['rice', 'wheat', 'grain', 'harvest', 'farm', 'agriculture'] },
  { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'water', 'surf', 'beach', 'tsunami'] },
  { emoji: '🌈', keywords: ['rainbow', 'colors', 'pride', 'weather', 'arc', 'spectrum'] },
  { emoji: '☀️', keywords: ['sun', 'sunny', 'bright', 'weather', 'hot', 'summer', 'day'] },
  { emoji: '🌤️', keywords: ['sun', 'cloud', 'weather', 'partly', 'cloudy', 'day'] },
  { emoji: '⛅', keywords: ['cloud', 'sun', 'weather', 'partly', 'cloudy'] },
  { emoji: '🌙', keywords: ['moon', 'crescent', 'night', 'sleep', 'dark', 'lunar'] },
  { emoji: '🌍', keywords: ['earth', 'globe', 'world', 'planet', 'europe', 'africa'] },
  { emoji: '🌎', keywords: ['earth', 'globe', 'world', 'planet', 'americas'] },
  { emoji: '🌏', keywords: ['earth', 'globe', 'world', 'planet', 'asia', 'australia'] },
  { emoji: '🗺️', keywords: ['map', 'world', 'travel', 'geography', 'atlas'] },
  { emoji: '🧭', keywords: ['compass', 'direction', 'navigation', 'north', 'travel'] },
  { emoji: '⛰️', keywords: ['mountain', 'peak', 'climb', 'nature', 'high', 'hill'] },

  // PEOPLE & EMOTIONS
  { emoji: '😀', keywords: ['smile', 'happy', 'grin', 'face', 'joy', 'cheerful'] },
  { emoji: '😃', keywords: ['smile', 'happy', 'face', 'joy', 'big', 'eyes'] },
  { emoji: '😄', keywords: ['smile', 'happy', 'grin', 'face', 'eyes', 'laugh'] },
  { emoji: '😁', keywords: ['grin', 'smile', 'happy', 'beam', 'face', 'teeth'] },
  { emoji: '😊', keywords: ['smile', 'blush', 'happy', 'warm', 'cute', 'shy'] },
  { emoji: '🥰', keywords: ['love', 'hearts', 'smile', 'adore', 'affection', 'happy'] },
  { emoji: '😍', keywords: ['love', 'heart', 'eyes', 'crush', 'adore', 'wow'] },
  { emoji: '🤩', keywords: ['star', 'eyes', 'excited', 'wow', 'amazing', 'starstruck'] },
  { emoji: '😎', keywords: ['cool', 'sunglasses', 'confident', 'chill', 'awesome'] },
  { emoji: '🤓', keywords: ['nerd', 'glasses', 'geek', 'smart', 'study'] },
  { emoji: '🧐', keywords: ['monocle', 'think', 'investigate', 'curious', 'examine'] },
  { emoji: '👍', keywords: ['thumbs', 'up', 'good', 'yes', 'approve', 'like', 'ok'] },
  { emoji: '👎', keywords: ['thumbs', 'down', 'bad', 'no', 'disapprove', 'dislike'] },
  { emoji: '👏', keywords: ['clap', 'applause', 'bravo', 'congratulations', 'hands'] },
  { emoji: '🙌', keywords: ['hands', 'raised', 'celebrate', 'hooray', 'praise', 'yay'] },
  { emoji: '🤝', keywords: ['handshake', 'deal', 'agreement', 'partnership', 'hello'] },
  { emoji: '🙏', keywords: ['pray', 'please', 'thank', 'hope', 'wish', 'namaste', 'hands'] },
  { emoji: '✊', keywords: ['fist', 'power', 'punch', 'fight', 'solidarity', 'strong'] },
  { emoji: '👊', keywords: ['fist', 'bump', 'punch', 'bro', 'pound', 'fight'] },
  { emoji: '🤛', keywords: ['fist', 'left', 'bump', 'punch'] },
  { emoji: '🤜', keywords: ['fist', 'right', 'bump', 'punch'] },
  { emoji: '✌️', keywords: ['peace', 'victory', 'two', 'fingers', 'v'] },
  { emoji: '🤞', keywords: ['crossed', 'fingers', 'luck', 'hope', 'wish'] },
  { emoji: '🤟', keywords: ['love', 'you', 'hand', 'rock', 'sign'] },
  { emoji: '🤘', keywords: ['rock', 'horns', 'metal', 'devil', 'hand'] },
  { emoji: '👋', keywords: ['wave', 'hello', 'hi', 'bye', 'hand', 'greeting'] },
  { emoji: '🖐️', keywords: ['hand', 'five', 'palm', 'fingers', 'stop'] },
  { emoji: '✋', keywords: ['hand', 'stop', 'raised', 'high', 'five'] },
  { emoji: '👆', keywords: ['point', 'up', 'finger', 'direction', 'above'] },
  { emoji: '👇', keywords: ['point', 'down', 'finger', 'direction', 'below'] },
  { emoji: '👈', keywords: ['point', 'left', 'finger', 'direction', 'back'] },
  { emoji: '👉', keywords: ['point', 'right', 'finger', 'direction', 'forward'] },

  // FOOD & DRINK
  { emoji: '☕', keywords: ['coffee', 'cafe', 'hot', 'drink', 'morning', 'tea', 'cup'] },
  { emoji: '🍵', keywords: ['tea', 'green', 'cup', 'drink', 'hot', 'matcha'] },
  { emoji: '🍺', keywords: ['beer', 'drink', 'mug', 'alcohol', 'bar', 'cheers'] },
  { emoji: '🍷', keywords: ['wine', 'glass', 'drink', 'red', 'alcohol', 'dinner'] },
  { emoji: '🍸', keywords: ['cocktail', 'martini', 'drink', 'bar', 'alcohol'] },
  { emoji: '🍹', keywords: ['tropical', 'drink', 'cocktail', 'vacation', 'summer'] },
  { emoji: '🧃', keywords: ['juice', 'box', 'drink', 'kids', 'straw'] },
  { emoji: '🍕', keywords: ['pizza', 'food', 'slice', 'italian', 'cheese', 'pepperoni'] },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'food', 'fast', 'cheeseburger'] },
  { emoji: '🍟', keywords: ['fries', 'french', 'food', 'fast', 'potato', 'chips'] },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'food', 'tuesday'] },
  { emoji: '🌯', keywords: ['burrito', 'wrap', 'mexican', 'food'] },
  { emoji: '🍜', keywords: ['noodles', 'ramen', 'soup', 'asian', 'food', 'bowl'] },
  { emoji: '🍣', keywords: ['sushi', 'japanese', 'food', 'fish', 'rice'] },
  { emoji: '🍰', keywords: ['cake', 'dessert', 'sweet', 'birthday', 'slice'] },
  { emoji: '🎂', keywords: ['birthday', 'cake', 'celebrate', 'party', 'candles'] },
  { emoji: '🍩', keywords: ['donut', 'doughnut', 'dessert', 'sweet', 'breakfast'] },
  { emoji: '🍪', keywords: ['cookie', 'dessert', 'sweet', 'biscuit', 'snack'] },
  { emoji: '🍫', keywords: ['chocolate', 'candy', 'sweet', 'bar', 'dessert'] },
  { emoji: '🍎', keywords: ['apple', 'red', 'fruit', 'healthy', 'teacher'] },
  { emoji: '🍊', keywords: ['orange', 'fruit', 'citrus', 'tangerine'] },
  { emoji: '🍋', keywords: ['lemon', 'fruit', 'citrus', 'yellow', 'sour'] },
  { emoji: '🍇', keywords: ['grapes', 'fruit', 'wine', 'purple', 'vine'] },
  { emoji: '🍓', keywords: ['strawberry', 'fruit', 'red', 'berry', 'sweet'] },
  { emoji: '🥑', keywords: ['avocado', 'fruit', 'green', 'guacamole', 'healthy'] },

  // ANIMALS
  { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'animal', 'cute', 'face'] },
  { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'animal', 'cute', 'face'] },
  { emoji: '🐭', keywords: ['mouse', 'animal', 'rodent', 'cute', 'face'] },
  { emoji: '🐰', keywords: ['rabbit', 'bunny', 'animal', 'cute', 'easter', 'face'] },
  { emoji: '🦊', keywords: ['fox', 'animal', 'cunning', 'cute', 'red'] },
  { emoji: '🐻', keywords: ['bear', 'animal', 'teddy', 'cute', 'face'] },
  { emoji: '🐼', keywords: ['panda', 'animal', 'bear', 'cute', 'china', 'bamboo'] },
  { emoji: '🐨', keywords: ['koala', 'animal', 'australia', 'cute', 'bear'] },
  { emoji: '🦁', keywords: ['lion', 'animal', 'king', 'jungle', 'face', 'mane'] },
  { emoji: '🐯', keywords: ['tiger', 'animal', 'stripes', 'jungle', 'face'] },
  { emoji: '🐮', keywords: ['cow', 'animal', 'farm', 'moo', 'face'] },
  { emoji: '🐷', keywords: ['pig', 'animal', 'farm', 'oink', 'face', 'pink'] },
  { emoji: '🐸', keywords: ['frog', 'animal', 'amphibian', 'face', 'green'] },
  { emoji: '🐵', keywords: ['monkey', 'animal', 'ape', 'face', 'cute'] },
  { emoji: '🦄', keywords: ['unicorn', 'magic', 'fantasy', 'horse', 'rainbow', 'mythical'] },
  { emoji: '🐴', keywords: ['horse', 'animal', 'face', 'pony'] },
  { emoji: '🦋', keywords: ['butterfly', 'insect', 'beautiful', 'nature', 'transform'] },
  { emoji: '🐝', keywords: ['bee', 'insect', 'honey', 'buzz', 'yellow'] },
  { emoji: '🐛', keywords: ['bug', 'insect', 'caterpillar', 'worm', 'nature'] },
  { emoji: '🦅', keywords: ['eagle', 'bird', 'fly', 'america', 'freedom'] },
  { emoji: '🦉', keywords: ['owl', 'bird', 'wise', 'night', 'hoot'] },
  { emoji: '🐦', keywords: ['bird', 'twitter', 'fly', 'chirp', 'animal'] },
  { emoji: '🐧', keywords: ['penguin', 'bird', 'animal', 'cold', 'linux'] },
  { emoji: '🐢', keywords: ['turtle', 'slow', 'animal', 'shell', 'reptile'] },
  { emoji: '🐍', keywords: ['snake', 'python', 'reptile', 'animal', 'slither'] },
  { emoji: '🦈', keywords: ['shark', 'fish', 'ocean', 'jaws', 'danger'] },
  { emoji: '🐙', keywords: ['octopus', 'sea', 'ocean', 'tentacles', 'animal'] },
  { emoji: '🦀', keywords: ['crab', 'sea', 'ocean', 'beach', 'cancer'] },
  { emoji: '🐳', keywords: ['whale', 'ocean', 'sea', 'spout', 'animal', 'big'] },
  { emoji: '🐬', keywords: ['dolphin', 'ocean', 'sea', 'smart', 'flipper'] },

  // SYMBOLS & SHAPES
  { emoji: '❤️', keywords: ['heart', 'love', 'red', 'romance', 'valentine', 'like'] },
  { emoji: '🧡', keywords: ['heart', 'orange', 'love'] },
  { emoji: '💛', keywords: ['heart', 'yellow', 'love', 'friendship'] },
  { emoji: '💚', keywords: ['heart', 'green', 'love', 'jealous', 'envy'] },
  { emoji: '💙', keywords: ['heart', 'blue', 'love', 'trust'] },
  { emoji: '💜', keywords: ['heart', 'purple', 'love'] },
  { emoji: '🖤', keywords: ['heart', 'black', 'love', 'dark'] },
  { emoji: '🤍', keywords: ['heart', 'white', 'love', 'pure'] },
  { emoji: '💔', keywords: ['heart', 'broken', 'sad', 'breakup', 'hurt'] },
  { emoji: '♠️', keywords: ['spade', 'card', 'game', 'poker', 'suit'] },
  { emoji: '♥️', keywords: ['heart', 'card', 'game', 'poker', 'suit', 'love'] },
  { emoji: '♦️', keywords: ['diamond', 'card', 'game', 'poker', 'suit'] },
  { emoji: '♣️', keywords: ['club', 'card', 'game', 'poker', 'suit'] },
  { emoji: '🔷', keywords: ['diamond', 'blue', 'shape', 'large'] },
  { emoji: '🔶', keywords: ['diamond', 'orange', 'shape', 'large'] },
  { emoji: '🔵', keywords: ['circle', 'blue', 'shape', 'dot'] },
  { emoji: '🔴', keywords: ['circle', 'red', 'shape', 'dot', 'record'] },
  { emoji: '🟢', keywords: ['circle', 'green', 'shape', 'dot', 'go'] },
  { emoji: '🟡', keywords: ['circle', 'yellow', 'shape', 'dot'] },
  { emoji: '🟣', keywords: ['circle', 'purple', 'shape', 'dot'] },
  { emoji: '🟠', keywords: ['circle', 'orange', 'shape', 'dot'] },
  { emoji: '⚫', keywords: ['circle', 'black', 'shape', 'dot'] },
  { emoji: '⚪', keywords: ['circle', 'white', 'shape', 'dot'] },
  { emoji: '🔲', keywords: ['button', 'black', 'square', 'shape'] },
  { emoji: '🔳', keywords: ['button', 'white', 'square', 'shape'] },
  { emoji: '▪️', keywords: ['square', 'black', 'small', 'shape'] },
  { emoji: '▫️', keywords: ['square', 'white', 'small', 'shape'] },
  { emoji: '◾', keywords: ['square', 'black', 'medium', 'shape'] },
  { emoji: '◽', keywords: ['square', 'white', 'medium', 'shape'] },
  { emoji: '🚫', keywords: ['no', 'prohibited', 'forbidden', 'stop', 'ban'] },
  { emoji: '⛔', keywords: ['no', 'entry', 'stop', 'forbidden', 'prohibited'] },
  { emoji: '⚠️', keywords: ['warning', 'caution', 'alert', 'danger', 'attention'] },
  { emoji: '🚧', keywords: ['construction', 'barrier', 'work', 'building', 'wip'] },
  { emoji: '♿', keywords: ['wheelchair', 'accessible', 'disability', 'handicap'] },
  { emoji: '🅿️', keywords: ['parking', 'car', 'sign', 'letter', 'p'] },
  { emoji: 'ℹ️', keywords: ['information', 'info', 'help', 'blue', 'i'] },
  { emoji: '🆕', keywords: ['new', 'fresh', 'latest', 'badge'] },
  { emoji: '🆙', keywords: ['up', 'upgrade', 'level', 'badge'] },
  { emoji: '🆗', keywords: ['ok', 'okay', 'good', 'badge', 'approve'] },
  { emoji: '🆒', keywords: ['cool', 'awesome', 'nice', 'badge'] },
  { emoji: '🆓', keywords: ['free', 'gratis', 'badge', 'cost'] },
  { emoji: '🔝', keywords: ['top', 'up', 'best', 'arrow'] },
  { emoji: '🔚', keywords: ['end', 'finish', 'arrow', 'complete'] },
  { emoji: '🔛', keywords: ['on', 'switch', 'arrow', 'active'] },
  { emoji: '🔜', keywords: ['soon', 'coming', 'arrow', 'future'] },
  { emoji: '🔙', keywords: ['back', 'return', 'arrow', 'previous'] },

  // COLLABORATION & TEAMWORK
  { emoji: '👥', keywords: ['people', 'team', 'group', 'users', 'collaboration', 'together', 'crowd'] },
  { emoji: '🗣️', keywords: ['speak', 'speaking', 'head', 'voice', 'talk', 'communication', 'discussion'] },
  { emoji: '👂', keywords: ['ear', 'listen', 'hearing', 'audio', 'sound', 'attention', 'feedback'] },
  { emoji: '🫂', keywords: ['hug', 'embrace', 'people', 'support', 'care', 'comfort', 'together'] },
  { emoji: '🙋', keywords: ['raise', 'hand', 'volunteer', 'question', 'ask', 'participate', 'engage'] },
  { emoji: '🧑‍🤝‍🧑', keywords: ['holding', 'hands', 'people', 'together', 'partnership', 'unity', 'team'] },
  { emoji: '👨‍💼', keywords: ['office', 'worker', 'business', 'man', 'professional', 'executive', 'manager'] },
  { emoji: '👩‍💼', keywords: ['office', 'worker', 'business', 'woman', 'professional', 'executive', 'manager'] },
  { emoji: '🧑‍💻', keywords: ['technologist', 'developer', 'programmer', 'coder', 'laptop', 'computer', 'tech'] },
  { emoji: '👨‍🏫', keywords: ['teacher', 'professor', 'instructor', 'educator', 'mentor', 'coach', 'guide'] },
  { emoji: '👩‍🏫', keywords: ['teacher', 'professor', 'instructor', 'educator', 'mentor', 'coach', 'guide'] },
  { emoji: '🤲', keywords: ['palms', 'up', 'open', 'hands', 'receive', 'give', 'offer', 'collaboration'] },
  { emoji: '🙇', keywords: ['bow', 'respect', 'apology', 'gratitude', 'humble', 'greeting'] },
  { emoji: '🗨️', keywords: ['speech', 'bubble', 'left', 'talk', 'message', 'chat', 'discuss'] },
  { emoji: '💁', keywords: ['information', 'desk', 'help', 'service', 'assist', 'present'] },
  { emoji: '🙆', keywords: ['ok', 'gesture', 'yes', 'accept', 'approve', 'agree'] },
  { emoji: '🙅', keywords: ['no', 'gesture', 'stop', 'deny', 'refuse', 'disagree'] },
  { emoji: '👨‍👩‍👧‍👦', keywords: ['family', 'team', 'group', 'together', 'household', 'unit'] },
  { emoji: '🫱🏻‍🫲🏼', keywords: ['handshake', 'diversity', 'inclusion', 'agreement', 'partnership', 'deal'] },
  { emoji: '🧑‍🎓', keywords: ['student', 'graduate', 'learner', 'education', 'study', 'school'] },

  // VISION & FORESIGHT
  { emoji: '👁️‍🗨️', keywords: ['eye', 'speech', 'witness', 'awareness', 'vision', 'see', 'observe'] },
  { emoji: '👓', keywords: ['glasses', 'eyewear', 'see', 'vision', 'clarity', 'read', 'spectacles'] },
  { emoji: '🥽', keywords: ['goggles', 'safety', 'vision', 'protect', 'lab', 'swim', 'vr'] },
  { emoji: '🌅', keywords: ['sunrise', 'dawn', 'morning', 'new', 'beginning', 'horizon', 'future'] },
  { emoji: '🌄', keywords: ['sunrise', 'mountains', 'dawn', 'vista', 'view', 'horizon', 'nature'] },
  { emoji: '🌆', keywords: ['cityscape', 'dusk', 'evening', 'urban', 'skyline', 'view', 'city'] },
  { emoji: '🌉', keywords: ['bridge', 'night', 'city', 'connection', 'span', 'crossing', 'view'] },
  { emoji: '🌌', keywords: ['milky', 'way', 'galaxy', 'space', 'stars', 'cosmos', 'universe', 'vision'] },
  { emoji: '🔆', keywords: ['bright', 'brightness', 'high', 'light', 'clarity', 'visible', 'clear'] },
  { emoji: '🔅', keywords: ['dim', 'low', 'brightness', 'light', 'subtle', 'soft'] },
  { emoji: '💠', keywords: ['diamond', 'dot', 'cute', 'kawaii', 'flower', 'sparkle', 'vision'] },
  { emoji: '🌠', keywords: ['shooting', 'star', 'night', 'wish', 'dream', 'vision', 'aspiration'] },
  { emoji: '🏙️', keywords: ['cityscape', 'urban', 'skyline', 'buildings', 'city', 'view', 'panorama'] },
  { emoji: '🔦', keywords: ['flashlight', 'torch', 'light', 'illuminate', 'search', 'vision', 'find'] },

  // ACTION & EXECUTION
  { emoji: '💨', keywords: ['dash', 'wind', 'fast', 'speed', 'running', 'action', 'quick', 'whoosh'] },
  { emoji: '▶️', keywords: ['play', 'start', 'begin', 'go', 'action', 'video', 'music', 'execute'] },
  { emoji: '⏩', keywords: ['fast', 'forward', 'speed', 'skip', 'advance', 'quick', 'accelerate'] },
  { emoji: '⏭️', keywords: ['next', 'track', 'skip', 'forward', 'advance', 'continue'] },
  { emoji: '⏯️', keywords: ['play', 'pause', 'toggle', 'control', 'media', 'action'] },
  { emoji: '🦸', keywords: ['superhero', 'hero', 'power', 'action', 'save', 'strong', 'cape'] },
  { emoji: '🦹', keywords: ['supervillain', 'villain', 'power', 'action', 'strong', 'cape'] },
  { emoji: '🏋️', keywords: ['weight', 'lifting', 'gym', 'strong', 'exercise', 'fitness', 'action'] },
  { emoji: '🤸', keywords: ['cartwheel', 'gymnastics', 'acrobat', 'action', 'flexible', 'sport'] },
  { emoji: '🥊', keywords: ['boxing', 'glove', 'fight', 'punch', 'action', 'sport', 'combat'] },
  { emoji: '🥋', keywords: ['martial', 'arts', 'karate', 'judo', 'action', 'discipline', 'uniform'] },
  { emoji: '🏌️', keywords: ['golf', 'swing', 'sport', 'action', 'precision', 'club'] },
  { emoji: '🤾', keywords: ['handball', 'sport', 'action', 'throw', 'ball', 'jump'] },
  { emoji: '🚀', keywords: ['rocket', 'launch', 'start', 'fast', 'action', 'blast', 'go', 'execute'] },
  { emoji: '⚡', keywords: ['lightning', 'power', 'fast', 'action', 'electric', 'quick', 'instant'] },
  { emoji: '🎯', keywords: ['target', 'bullseye', 'goal', 'aim', 'focus', 'action', 'hit', 'execute'] },
  { emoji: '🔨', keywords: ['hammer', 'build', 'action', 'tool', 'construct', 'work', 'create'] },

  // AI & ARTIFICIAL INTELLIGENCE
  { emoji: '⚛️', keywords: ['atom', 'science', 'physics', 'nuclear', 'quantum', 'ai', 'tech'] },
  { emoji: '🔢', keywords: ['numbers', 'input', 'data', 'math', 'calculate', 'ai', 'algorithm'] },
  { emoji: '🔣', keywords: ['symbols', 'input', 'characters', 'code', 'programming', 'ai'] },
  { emoji: '🔤', keywords: ['letters', 'alphabet', 'input', 'text', 'language', 'ai', 'nlp'] },
  { emoji: '🤯', keywords: ['mind', 'blown', 'exploding', 'head', 'amazed', 'ai', 'shocking', 'wow'] },
  { emoji: '🌐', keywords: ['globe', 'internet', 'web', 'worldwide', 'global', 'network', 'ai', 'connected'] },
  { emoji: '🎛️', keywords: ['control', 'knobs', 'adjust', 'settings', 'tune', 'configure', 'ai'] },
  { emoji: '🖲️', keywords: ['trackball', 'control', 'input', 'device', 'computer', 'interface'] },
  { emoji: '🧮', keywords: ['abacus', 'calculate', 'math', 'compute', 'counting', 'ai', 'algorithm'] },
  { emoji: '📟', keywords: ['pager', 'device', 'communication', 'tech', 'retro', 'message'] },
  { emoji: '🔐', keywords: ['locked', 'key', 'secure', 'encryption', 'password', 'security', 'ai'] },
  { emoji: '🛡️', keywords: ['shield', 'protect', 'security', 'defense', 'safe', 'guard', 'ai'] },
  { emoji: '🧿', keywords: ['nazar', 'eye', 'protection', 'ai', 'vision', 'watch', 'observe'] },

  // TECHNOLOGY & DIGITAL
  { emoji: '⌚', keywords: ['watch', 'time', 'smart', 'wearable', 'tech', 'apple', 'fitness'] },
  { emoji: '🔊', keywords: ['speaker', 'loud', 'sound', 'audio', 'volume', 'high', 'tech'] },
  { emoji: '🔉', keywords: ['speaker', 'medium', 'sound', 'audio', 'volume', 'tech'] },
  { emoji: '🔈', keywords: ['speaker', 'low', 'sound', 'audio', 'volume', 'quiet', 'tech'] },
  { emoji: '📢', keywords: ['loudspeaker', 'announce', 'broadcast', 'megaphone', 'public', 'tech'] },
  { emoji: '🎚️', keywords: ['slider', 'level', 'control', 'adjust', 'volume', 'mixing', 'tech'] },
  { emoji: '🎙️', keywords: ['microphone', 'studio', 'podcast', 'record', 'voice', 'audio', 'tech'] },
  { emoji: '🖨️', keywords: ['printer', 'print', 'document', 'paper', 'office', 'tech'] },
  { emoji: '💽', keywords: ['minidisc', 'storage', 'data', 'retro', 'music', 'tech'] },
  { emoji: '📼', keywords: ['videocassette', 'vhs', 'tape', 'retro', 'movie', 'video', 'tech'] },
  { emoji: '📠', keywords: ['fax', 'machine', 'document', 'send', 'office', 'retro', 'tech'] },
  { emoji: '🛜', keywords: ['wifi', 'wireless', 'internet', 'network', 'signal', 'connected', 'tech'] },
  { emoji: '🔓', keywords: ['unlock', 'open', 'access', 'security', 'password', 'tech'] },
  { emoji: '🔒', keywords: ['lock', 'secure', 'closed', 'private', 'security', 'protect', 'tech'] },
  { emoji: '🔏', keywords: ['lock', 'pen', 'privacy', 'secure', 'sign', 'tech'] },
  { emoji: '🗄️', keywords: ['cabinet', 'file', 'storage', 'archive', 'organize', 'office', 'tech'] },
  { emoji: '⏳', keywords: ['hourglass', 'time', 'waiting', 'loading', 'processing', 'patience'] },
  { emoji: '⌛', keywords: ['hourglass', 'done', 'time', 'complete', 'finished', 'elapsed'] },

  // PLANNING & ORGANIZATION
  { emoji: '📆', keywords: ['calendar', 'date', 'schedule', 'plan', 'event', 'tear', 'off'] },
  { emoji: '🗒️', keywords: ['notepad', 'spiral', 'notes', 'write', 'plan', 'list', 'todo'] },
  { emoji: '📒', keywords: ['ledger', 'notebook', 'record', 'accounting', 'plan', 'organize'] },
  { emoji: '🗃️', keywords: ['card', 'file', 'box', 'organize', 'index', 'storage', 'plan'] },
  { emoji: '🗳️', keywords: ['ballot', 'box', 'vote', 'election', 'decision', 'choice', 'plan'] },
  { emoji: '📂', keywords: ['folder', 'open', 'file', 'organize', 'directory', 'storage', 'plan'] },
  { emoji: '📁', keywords: ['folder', 'file', 'organize', 'directory', 'storage', 'plan'] },
  { emoji: '🗞️', keywords: ['newspaper', 'rolled', 'news', 'information', 'daily', 'read'] },
  { emoji: '🏁', keywords: ['checkered', 'flag', 'finish', 'race', 'goal', 'complete', 'end'] },
  { emoji: '🚩', keywords: ['flag', 'triangular', 'mark', 'milestone', 'important', 'alert'] },
  { emoji: '🎌', keywords: ['flags', 'crossed', 'celebrate', 'japan', 'festival', 'event'] },
  { emoji: '🏴', keywords: ['flag', 'black', 'pirate', 'anarchy', 'dark'] },
  { emoji: '🏳️', keywords: ['flag', 'white', 'surrender', 'peace', 'truce'] },
  { emoji: '📊', keywords: ['chart', 'bar', 'graph', 'data', 'analytics', 'plan', 'statistics'] },
  { emoji: '📈', keywords: ['chart', 'up', 'growth', 'trending', 'increase', 'plan', 'success'] },
  { emoji: '📉', keywords: ['chart', 'down', 'decrease', 'decline', 'loss', 'plan', 'trend'] },
  { emoji: '🧾', keywords: ['receipt', 'invoice', 'bill', 'purchase', 'record', 'plan'] },
  { emoji: '📑', keywords: ['bookmark', 'tabs', 'document', 'organize', 'pages', 'plan'] },

  // NAVIGATION & DIRECTION
  { emoji: '⬇️', keywords: ['arrow', 'down', 'south', 'direction', 'below', 'decrease', 'navigation'] },
  { emoji: '⬅️', keywords: ['arrow', 'left', 'west', 'direction', 'back', 'previous', 'navigation'] },
  { emoji: '↘️', keywords: ['arrow', 'diagonal', 'down', 'right', 'direction', 'navigation'] },
  { emoji: '↙️', keywords: ['arrow', 'diagonal', 'down', 'left', 'direction', 'navigation'] },
  { emoji: '↖️', keywords: ['arrow', 'diagonal', 'up', 'left', 'direction', 'navigation'] },
  { emoji: '↕️', keywords: ['arrow', 'up', 'down', 'vertical', 'direction', 'resize', 'navigation'] },
  { emoji: '↔️', keywords: ['arrow', 'left', 'right', 'horizontal', 'direction', 'resize', 'navigation'] },
  { emoji: '🔃', keywords: ['arrows', 'clockwise', 'rotate', 'refresh', 'sync', 'navigation'] },
  { emoji: '🔂', keywords: ['repeat', 'single', 'once', 'loop', 'track', 'navigation'] },
  { emoji: '⤴️', keywords: ['arrow', 'curved', 'up', 'right', 'direction', 'reply', 'navigation'] },
  { emoji: '⤵️', keywords: ['arrow', 'curved', 'down', 'right', 'direction', 'navigation'] },
  { emoji: '🔼', keywords: ['triangle', 'up', 'button', 'arrow', 'increase', 'navigation'] },
  { emoji: '🔽', keywords: ['triangle', 'down', 'button', 'arrow', 'decrease', 'navigation'] },
  { emoji: '◀️', keywords: ['triangle', 'left', 'back', 'previous', 'rewind', 'navigation'] },
  { emoji: '⏪', keywords: ['rewind', 'fast', 'back', 'reverse', 'previous', 'navigation'] },
  { emoji: '⏫', keywords: ['fast', 'up', 'double', 'arrow', 'top', 'navigation'] },
  { emoji: '⏬', keywords: ['fast', 'down', 'double', 'arrow', 'bottom', 'navigation'] },
  { emoji: '🛤️', keywords: ['railway', 'track', 'train', 'path', 'direction', 'navigation', 'route'] },
  { emoji: '🛣️', keywords: ['motorway', 'highway', 'road', 'path', 'direction', 'navigation', 'route'] },
  { emoji: '🛫', keywords: ['departures', 'airplane', 'takeoff', 'travel', 'airport', 'navigation'] },
  { emoji: '🛬', keywords: ['arrivals', 'airplane', 'landing', 'travel', 'airport', 'navigation'] },
  { emoji: '🚏', keywords: ['bus', 'stop', 'station', 'transit', 'public', 'navigation'] },
  { emoji: '🚥', keywords: ['traffic', 'light', 'horizontal', 'signal', 'road', 'navigation'] },
  { emoji: '🚦', keywords: ['traffic', 'light', 'vertical', 'signal', 'road', 'navigation'] },
  { emoji: '🧳', keywords: ['luggage', 'baggage', 'travel', 'suitcase', 'trip', 'navigation'] },
  { emoji: '🗻', keywords: ['mount', 'fuji', 'mountain', 'japan', 'peak', 'destination', 'navigation'] },
  { emoji: '🏔️', keywords: ['mountain', 'snow', 'peak', 'nature', 'destination', 'navigation'] },
  { emoji: '⛳', keywords: ['flag', 'hole', 'golf', 'destination', 'goal', 'target', 'navigation'] },
  { emoji: '🎪', keywords: ['circus', 'tent', 'destination', 'event', 'venue', 'location'] },
  { emoji: '🏟️', keywords: ['stadium', 'venue', 'sports', 'destination', 'event', 'location'] },
  { emoji: '🏛️', keywords: ['classical', 'building', 'government', 'destination', 'landmark', 'location'] },
];

// Quick access array of just emojis for random selection
export const GOAL_ICONS = SEARCHABLE_ICONS.map(icon => icon.emoji);

// Get a random icon from the set
export const getRandomIcon = (): string => {
  const index = Math.floor(Math.random() * GOAL_ICONS.length);
  return GOAL_ICONS[index];
};

// Get the default icon (first in list)
export const getDefaultIcon = (): string => {
  return GOAL_ICONS[0];
};

// Search icons by keyword
export const searchIcons = (query: string): string[] => {
  if (!query.trim()) return GOAL_ICONS;

  const lowerQuery = query.toLowerCase().trim();

  return SEARCHABLE_ICONS
    .filter(icon =>
      icon.keywords.some(keyword => keyword.includes(lowerQuery)) ||
      icon.emoji === query
    )
    .map(icon => icon.emoji);
};
