// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mraabitlkqvvnchnrbby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYWFiaXRsa3F2dm5jaG5yYmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDcyMzAsImV4cCI6MjA2NjQ4MzIzMH0.vaqtufepwKtqLSoOh5_bjH6DvhiRsdqpN_aXcSfOmtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);